#!/usr/bin/env python3
"""
Generate a small INT8 DS-CNN wake-word model for TFLite Micro.

*** THE WEIGHTS ARE RANDOMLY INITIALISED. THIS MODEL IS UNTRAINED. ***

It exists to measure the RUNTIME infrastructure -- tensor arena size, model
footprint, inference latency, tensor shapes -- on a graph with the correct
architecture and the correct INT8 quantisation. It says NOTHING about
wake-word accuracy, false-accept rate, or false-reject rate. Those numbers
require a trained model evaluated against a real labelled dataset.

Architecture follows DS-CNN (Zhang et al., "Hello Edge", 2017), narrowed to
32 channels to suit a 256 KB RAM budget:

  input 1 x T x 40 x 1  int8
    Conv2D 32 @ (10,4) stride (2,2) + ReLU
    4x [ DepthwiseConv2D (3,3) + ReLU , Conv2D 32 @ (1,1) + ReLU ]
    GlobalAveragePooling
    Dense 2  (not-wake / wake)
    Softmax
"""
import numpy as np
import tensorflow as tf

T_FRAMES = 25      # 25 frames x 20 ms hop = 500 ms context window
N_MELS   = 40
N_CLASS  = 2

def build():
    inp = tf.keras.Input(shape=(T_FRAMES, N_MELS, 1), name="mel")
    x = tf.keras.layers.Conv2D(32, (10, 4), strides=(2, 2), padding="same",
                               use_bias=True, activation="relu")(inp)
    for _ in range(4):
        x = tf.keras.layers.DepthwiseConv2D((3, 3), padding="same",
                                            use_bias=True, activation="relu")(x)
        x = tf.keras.layers.Conv2D(32, (1, 1), padding="same",
                                   use_bias=True, activation="relu")(x)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    out = tf.keras.layers.Dense(N_CLASS, activation="softmax", name="score")(x)
    return tf.keras.Model(inp, out, name="ds_cnn_kws")

def representative():
    # Random data: the model is untrained, so the calibration set only has to
    # exercise the activation ranges, not represent real speech.
    rng = np.random.default_rng(0)
    for _ in range(200):
        yield [rng.standard_normal((1, T_FRAMES, N_MELS, 1)).astype(np.float32) * 3.0]

m = build()
m.summary()
n_params = m.count_params()

conv = tf.lite.TFLiteConverter.from_keras_model(m)
conv.optimizations = [tf.lite.Optimize.DEFAULT]
conv.representative_dataset = representative
conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
conv.inference_input_type = tf.int8
conv.inference_output_type = tf.int8
tfl = conv.convert()

open("ds_cnn_int8.tflite", "wb").write(tfl)

# Emit a C array for embedding in flash.
with open("../main/ds_cnn_model_data.cc", "w") as f:
    f.write('// GENERATED by model/gen_model.py -- do not edit.\n')
    f.write('// *** UNTRAINED PLACEHOLDER MODEL: random weights, no accuracy claim. ***\n')
    f.write('#include "ds_cnn_model_data.h"\n\n')
    f.write('const unsigned int g_ds_cnn_model_len = %d;\n' % len(tfl))
    f.write('alignas(16) const unsigned char g_ds_cnn_model[] = {\n')
    for i in range(0, len(tfl), 12):
        f.write('  ' + ' '.join('0x%02x,' % b for b in tfl[i:i+12]) + '\n')
    f.write('};\n')

with open("../main/include/ds_cnn_model_data.h", "w") as f:
    f.write('#pragma once\n')
    f.write('extern const unsigned char g_ds_cnn_model[];\n')
    f.write('extern const unsigned int g_ds_cnn_model_len;\n')

print("\n=== MODEL GENERATED ===")
print("params            :", n_params)
print("tflite bytes      :", len(tfl))
print("input  shape      : (1, %d, %d, 1) int8" % (T_FRAMES, N_MELS))
print("output shape      : (1, %d) int8" % N_CLASS)
print("context window    : %d frames x %d ms = %d ms" % (T_FRAMES, 20, T_FRAMES*20))
print("*** WEIGHTS ARE RANDOM -- UNTRAINED -- NO ACCURACY CLAIMED ***")
